# Generated by Django 4.1.3 on 2022-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conditions", models.JSONField(null=True)),
                ("parent", models.IntegerField(blank=True, default=None, null=True)),
                ("is_stopping", models.BooleanField(blank=True, null=True)),
                ("conclusion", models.CharField(blank=True, max_length=200, null=True)),
                ("if_true", models.IntegerField(blank=True, default=None, null=True)),
                ("if_false", models.IntegerField(blank=True, default=None, null=True)),
                ("cornerstones", models.JSONField(null=True)),
            ],
        ),
    ]
