# Generated by Django 4.1.3 on 2022-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdr_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="is_stopping",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
