# Generated by Django 4.1.3 on 2022-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdr_core", "0002_alter_rule_is_stopping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="cornerstones",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
