# Generated by Django 4.1.3 on 2022-12-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdr_core", "0003_alter_rule_cornerstones"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="cornerstones",
            new_name="cornerstone",
        ),
    ]
