# Generated by Django 4.1.3 on 2023-01-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdr_core", "0004_rename_cornerstones_rule_cornerstone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
